- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packagess"
  become: yes
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  command: npm install -g pm2@3.2.2
- name: declare variables
  become: yes
  shell: |
    export ENVIRONMENT=production
    export TYPEORM_ENTITIES="./modules/domain/**/*.entity.js"
    export TYPEORM_MIGRATIONS="./migrations/*.js"
    export TYPEORM_MIGRATIONS_DIR="./migrations"
    export TYPEORM_CONNECTION="postgres"
    export TYPEORM_HOST="udapeople-db.cyxovfwoscrk.us-east-1.rds.amazonaws.com"
    export TYPEORM_USERNAME="udapeople"
    export TYPEORM_PASSWORD="udapeople123"
    export TYPEORM_DATABASE="postgres"
    export TYPEORM_PORT=5432