# - name: "unarchive artifact.tar.gz "
#   become: yes
#   unarchive:
#     src: artifact.tar.gz
#     dest: /home/ubuntu
# - name: chown
#   become: yes
#   file:
#     path: /home/ubuntu
#     owner: ubuntu
#     group: ubuntu
#     recurse: yes

- name: install and start app
  command: |
    npm install
    pm2 stop default
    pm2 start npm -- start
  args:
    chdir: /home/ubuntu/backend
  # environment:
  #   ENVIRONMENT: production
  #   TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
  #   TYPEORM_MIGRATIONS_DIR: "./src/migrations"
  #   TYPEORM_MIGRATIONS: "./src/migrations/*.ts"
  #   TYPEORM_ENTITIES: "./src/modules/domain/**/*.entity.ts"
  #   TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
  #   TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
  #   TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
  #   TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
  #   TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"